name: Fire Call Monitor

on:
  schedule:
    - cron: '*/1 * * * *'  # every 1 minute
  workflow_dispatch:  # allows manual runs

jobs:
  run-fire-call-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python fire_call_script.py
